### ISSUE TITLE
Error: Bad response status code 502

### ISSUE THREAD

**Issue by w-abdullah** [recurly/recurly-js#429]
We have code running in production which was working fine until a few hours ago. But now it has started throwing 502 error

```
{ Error: Bad response status code 502
    at ClientRequest.handleResponse (/home/projectName/node_modules/plotly/index.js:237:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20) msg: undefined }
```

**Comment by chrissrogers** [comment]
@w-abdullah -- are you able to take a screenshot of your browser's network tab showing the request that is throwing the 502? The url, request and response headers, and request and response body would be most helpful.

**Comment by w-abdullah** [comment]
@chrissrogers Nope,

It's fixed for now. I will surely post above mentioned information if this happens again.
Closing issue for now.

Thanks.
